#ifndef CONFIGURATION_PRUSA_H
#include "MK3S.h"
#define CONFIGURATION_PRUSA_H

// Printer revision
#undef PRINTER_MMU_TYPE
#define PRINTER_MMU_TYPE PRINTER_MK3S_MMU2
#undef PRINTER_MMU_NAME
#define PRINTER_MMU_NAME PRINTER_MK3S_MMU2_NAME

#endif //__CONFIGURATION_PRUSA_H
