/**
 * French
 *
 * LCD Menu Messages
 * Please note these are limited to 17 characters!
 *
 */

#define WELCOME_MSG							CUSTOM_MENDEL_NAME " prete."
#define MSG_SD_INSERTED						"Carte inseree"
#define MSG_SD_REMOVED						"Carte retiree "
#define MSG_MAIN							"Menu principal"
#define MSG_DISABLE_STEPPERS				"Arreter moteurs"
#define MSG_AUTO_HOME						"Origine auto."
#define MSG_SET_HOME_OFFSETS				"Regl. decal. origine"
#define MSG_SET_ORIGIN						"Regler origine"
#define MSG_COOLDOWN						"Refroidir"
#define MSG_SWITCH_PS_ON					"Allumer alim."
#define MSG_SWITCH_PS_OFF					"Eteindre alim."
#define MSG_MOVE_AXIS						"Deplacer un axe"
#define MSG_MOVE_X							"Deplacer X"
#define MSG_MOVE_Y							"Deplacer Y"
#define MSG_MOVE_Z							"Deplacer Z"
#define MSG_MOVE_E							"Extruder"
#define MSG_SPEED							"Vitesse"
#define MSG_NOZZLE							"Buse"
#define MSG_NOZZLE1							"Buse2"
#define MSG_NOZZLE2							"Buse3"
#define MSG_BED								"Lit"
#define MSG_FAN_SPEED						"Vitesse ventil."
#define MSG_FLOW							"Flux"
#define MSG_FLOW0							"Flux 0"
#define MSG_FLOW1							"Flux 1"
#define MSG_FLOW2							"Flux 2"
#define MSG_CONTROL							"Controler"
#define MSG_MIN								" \002 Min"
#define MSG_MAX								" \002 Max"
#define MSG_FACTOR							" \002 Fact"
#define MSG_TEMPERATURE						"Temperature"
#define MSG_MOTION							"Mouvement"
#define MSG_VOLUMETRIC						"Filament"
#define MSG_VOLUMETRIC_ENABLED				"E en mm3"
#define MSG_STORE_EPROM						"Sauver config"
#define MSG_LOAD_EPROM						"Lire config"
#define MSG_RESTORE_FAILSAFE				"Restaurer defauts"
#define MSG_REFRESH							"Actualiser"
#define MSG_WATCH							"Surveiller"
#define MSG_TUNE							"Regler"
#define MSG_PAUSE_PRINT						"Interrompre impr."
#define MSG_RESUME_PRINT					"Reprendre impr."
#define MSG_STOP_PRINT						"Arreter impr."
#define MSG_CARD_MENU						"Impr. depuis SD"
#define MSG_NO_CARD							"Pas de carte"
#define MSG_DWELL							"Repos..."
#define MSG_USERWAIT						"Atten. de l'util."
#define MSG_RESUMING						"Repri. de l'impr."
#define MSG_PRINT_ABORTED					"Impr. Annulee"
#define MSG_NO_MOVE							"Moteurs bloques."
#define MSG_KILLED							"MORT."
#define MSG_STOPPED							"STOPPE."
#define MSG_FILAMENTCHANGE					"Changer filament"
#define MSG_INIT_SDCARD						"Init. la carte SD"
#define MSG_CNG_SDCARD						"Changer de carte"
#define MSG_BABYSTEP_X						"Babystep X"
#define MSG_BABYSTEP_Y						"Babystep Y"
#define MSG_BABYSTEP_Z						"Live Z regler"
#define MSG_ADJUSTZ							"Auto Z regler?"
#define MSG_PICK_Z							"Choisir imprimer"

#define MSG_SETTINGS						"Reglage"
#define MSG_PREHEAT							"Prechauffage"
#define MSG_UNLOAD_FILAMENT					"Decharger filament"
#define MSG_LOAD_FILAMENT					"Charger filament"
#define MSG_LOAD_FILAMENT_1					"Charger filament 1"
#define MSG_LOAD_FILAMENT_2					"Charger filament 2"
#define MSG_LOAD_FILAMENT_3					"Charger filament 3"
#define MSG_LOAD_FILAMENT_4					"Charger filament 4"
#define MSG_UNLOAD_FILAMENT_1				"Decharger filament 1"
#define MSG_UNLOAD_FILAMENT_2				"Decharger filament 2"
#define MSG_UNLOAD_FILAMENT_3				"Decharger filament 3"
#define MSG_UNLOAD_FILAMENT_4				"Decharger filament 4"
#define MSG_UNLOAD_ALL						"Decharger tout"
#define MSG_LOAD_ALL						"Charger tout"

#define MSG_RECTRACT                        "Retraction"
#define MSG_ERROR                        	"ERROR:"
#define MSG_PREHEAT_NOZZLE       			"Prechauff. buse!"
#define MSG_SUPPORT							"Support"
#define MSG_CORRECTLY						"Changer ok?"
#define MSG_YES								"Oui"
#define MSG_NO								"Non"
#define MSG_NOT_LOADED 						"Filament non charge"
#define MSG_NOT_COLOR 						"Couleur pas claire"
#define MSG_LOADING_FILAMENT				"Chargement filament"
#define MSG_PLEASE_WAIT						"Attende svp"
#define MSG_LOADING_COLOR					"Charger couleur"
#define MSG_CHANGE_SUCCESS					"Changer succes!"
#define MSG_PRESS							" presser bouton"
#define MSG_INSERT_FILAMENT					"Inserer filament"
#define MSG_CHANGING_FILAMENT				"Filament-changement!"


#define MSG_SILENT_MODE_ON					"Mode [silencieux]"
#define MSG_SILENT_MODE_OFF					"Mode[haute force]"
#define MSG_AUTO_MODE_ON					"Mode[automatique]"
#define MSG_REBOOT							"Rebooter l'impri."
#define MSG_TAKE_EFFECT						" pour prendre effet"

#define MSG_Enqueing						"enqueuing \"
#define MSG_POWERUP							"Allumer"
#define MSG_CONFIGURATION_VER               " Last Updated: "
#define MSG_FREE_MEMORY                     " Free Memory"
#define MSG_PLANNER_BUFFER_BYTES            " PlannerBufferBytes: "
#define MSG_OK                              "ok"
#define MSG_ERR_CHECKSUM_MISMATCH           "checksum mismatch, Last Line: " //Checksum Fehler, Letzte Zeile: "
#define MSG_ERR_NO_CHECKSUM                 "No Checksum with line number, Last Line: " //Keine Checksum mit Zeilennummer, Letzte Zeile: "
#define MSG_BEGIN_FILE_LIST                 "Begin file list"
#define MSG_END_FILE_LIST                   "End file list"
#define MSG_M104_INVALID_EXTRUDER 			"M104 invalide extruder"
#define MSG_M105_INVALID_EXTRUDER			"M105 invalide extruder"
#define MSG_M200_INVALID_EXTRUDER			"M200 invalide extruder"
#define MSG_M218_INVALID_EXTRUDER			"M218 invalide extruder"
#define MSG_M221_INVALID_EXTRUDER			"M221 invalide extruder"
#define MSG_ERR_NO_THERMISTORS				"Pas de thermistances - pas de temperature"
#define MSG_M109_INVALID_EXTRUDER			"M109 invalide Extruder"
#define MSG_HEATING							"Prechauffage"
#define MSG_HEATING_COMPLETE				"Prechauffage OK"
#define MSG_BED_HEATING						"Prechauffage lit"
#define MSG_BED_DONE						"Lit OK"
#define MSG_M115_REPORT						"FIRMWARE_NAME:Marlin V1.0.2; Sprinter/grbl mashup for gen6 FIRMWARE_URL:" FIRMWARE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" CUSTOM_MENDEL_NAME " EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) " UUID:" MACHINE_UUID "\n"
#define MSG_ERR_KILLED          			"Printer halted. kill() called!"
#define MSG_ERR_STOPPED						"Imprimante arretee en raison d'erreurs. Corrigez l'erreur et utilisez M999 pour redemarrer. (La temperature est reinitialisee, reglez-la apres le redemarrage)"
#define MSG_RESEND							"Renvoyer: "
#define MSG_M119_REPORT                     "Reporting endstop status"
#define MSG_ENDSTOP_HIT						"declenche"
#define MSG_ENDSTOP_OPEN					"ouvert"

#define MSG_SD_CANT_OPEN_SUBDIR				"Impos. d'ouvrir le sous-repertoire"
#define MSG_SD_INIT_FAIL					"SD init echoue"
#define MSG_SD_VOL_INIT_FAIL				"volume.init a echoue"
#define MSG_SD_OPENROOT_FAIL				"L'acces au repertoire de base a echoue"
#define MSG_SD_CARD_OK						"SD carte ok"
#define MSG_SD_WORKDIR_FAIL					"Ouvrir le repertoire de travail a echoue"
#define MSG_SD_OPEN_FILE_FAIL				"Impossible d'ouvrir le fichier: "
#define MSG_SD_FILE_OPENED					"Fichier ouvert: "
#define MSG_SD_FILE_SELECTED				"Fichier choisi"
#define MSG_SD_WRITE_TO_FILE				"Ecrire dans le fichier: "
#define MSG_SD_PRINTING_BYTE                "SD printing byte "
#define MSG_SD_NOT_PRINTING					"Pas d'impression SD"
#define MSG_SD_ERR_WRITE_TO_FILE			"Erreur d'ecriture dans le fichier"
#define MSG_SD_CANT_ENTER_SUBDIR			"Sous-repertoire de probleme d'acces: "
/* to be translated
#define MSG_STEPPER_TOO_HIGH                "Schrittrate zu hoch"
#define MSG_ENDSTOPS_HIT                    "Endanstop erreicht"
#define MSG_ERR_COLD_EXTRUDE_STOP           "Stop, Extruder kalt!"
#define MSG_BABYSTEPPING_X                  "Babystepping X"
#define MSG_BABYSTEPPING_Y                  "Babystepping Y"
#define MSG_BABYSTEPPING_Z                  "Z wurde eingestellt"
#define MSG_SERIAL_ERROR_MENU_STRUCTURE     "Menuestruktur fehlerhaft"
*/
#define MSG_LANGUAGE_NAME					"Francais"
/*
#define MSG_LANGUAGE_SELECT					"Waehle Sprache"
#define MSG_PRUSA3D							"prusa3d.com"
#define MSG_PRUSA3D_FORUM					"forum.prusa3d.com"
#define MSG_PRUSA3D_HOWTO					"howto.prusa3d.com"

#define MSG_SELFTEST_ERROR					"Selbsttest Fehler !"
#define MSG_SELFTEST_PLEASECHECK			"Bitte pruefe:"
#define MSG_SELFTEST_NOTCONNECTED			"Nicht angeschlossen"
#define MSG_SELFTEST_HEATERTHERMISTOR		"Heater/Thermistor"
#define MSG_SELFTEST_BEDHEATER				"Bed / Heater"
#define MSG_SELFTEST_WIRINGERROR			"Verdrahtungsfehler"
#define MSG_SELFTEST_ENDSTOPS				"Endschalter"
#define MSG_SELFTEST_MOTOR					"Motor"
#define MSG_SELFTEST_ENDSTOP				"Endstop"
#define MSG_SELFTEST_ENDSTOP_NOTHIT 		"Endsch. n. erreicht"
#define MSG_SELFTEST_OK						"Selbsttest OK"
#define MSG_LOOSE_PULLEY					"Loser pulley"

#define MSG_SELFTEST_FAN					"Lueftertest";
#define MSG_SELFTEST_COOLING_FAN			"Vorderer Luefter?";
#define MSG_SELFTEST_EXTRUDER_FAN			"Linker Luefter?";
#define MSG_SELFTEST_FAN_YES				"Dreht";
#define MSG_SELFTEST_FAN_NO					"Dreht nicht";

#define MSG_STATS_TOTALFILAMENT				"Filament Gesamt:"
#define MSG_STATS_TOTALPRINTTIME 			"Totale Druckzeit:"
#define MSG_STATS_FILAMENTUSED				"Filamentverbrauch:"
#define MSG_STATS_PRINTTIME					"Druckzeit:  "
#define MSG_SELFTEST_START					"Selbsttest start "
#define MSG_SELFTEST_CHECK_ENDSTOPS			"Pruefe Endschalter  "
#define MSG_SELFTEST_CHECK_HOTEND			"Pruefe Hotend" 
#define MSG_SELFTEST_CHECK_X				"Pruefe X Achse    "
#define MSG_SELFTEST_CHECK_Y				"Pruefe Y Achse    "
#define MSG_SELFTEST_CHECK_Z				"Pruefe Z Achse    "
#define MSG_SELFTEST_CHECK_BED				"Pruefe Bett        "
#define MSG_SELFTEST_CHECK_ALLCORRECT		"Alles richtig    "
#define MSG_SELFTEST						"Selbsttest       "
#define MSG_SELFTEST_FAILED					"Selbsttest misluekt"
#define MSG_STATISTICS						"Statistiken "
#define MSG_USB_PRINTING					"Drucken ueber USB"
#define MSG_HOMEYZ                          "Kalibrieren Z"
#define MSG_HOMEYZ_PROGRESS                 "Kalibriere Z"
#define MSG_HOMEYZ_DONE		                "Kalibrierung OK"

#define MSG_SHOW_END_STOPS					"Anzeigen Enschalter"
#define MSG_CALIBRATE_BED					"Kalibrierung XYZ"
#define MSG_CALIBRATE_BED_RESET				"Reset XYZ Kalibr."

#define MSG_MOVE_CARRIAGE_TO_THE_TOP 		"Kalibrieren von XYZ. Drehen Sie den Knopf, bis beide Z-Schlitten obere Anschaege erreichen. Klicken wenn beide ganz oben sind."
#define MSG_MOVE_CARRIAGE_TO_THE_TOP_Z 		"Kalibrieren von Z. Drehen Sie den Knopf, bis beide Z-Schlitten obere Anschaege erreichen. Klicken wenn beide ganz oben sind."

#define MSG_FINISHING_MOVEMENTS							"Bewegung beenden"
#define MSG_PRINT_PAUSED								"Druck pausiert"
#define MSG_RESUMING_PRINT								"Druck weitergehen"
#define MSG_PID_EXTRUDER								"PID Kalibrierung"
#define MSG_SET_TEMPERATURE								"Temp. einsetzen"
#define MSG_PID_FINISHED								"PID Kalib. fertig"
#define MSG_PID_RUNNING									"PID Kalib."
#define MSG_CONFIRM_NOZZLE_CLEAN			"Bitte reinigen Sie die Buse vor Kalibrierung. Klicken wenn sauber."
#define MSG_CONFIRM_CARRIAGE_AT_THE_TOP		"Sind beide Z Schlitten ganz oben?"

#define MSG_CONFIRM_NOZZLE_CLEAN			"Bitte reinigen Sie die Buse vor Kalibrierung. Klicken wenn sauber."
#define MSG_CONFIRM_CARRIAGE_AT_THE_TOP		"Sind beide Z Schlitten ganz oben?"
#define MSG_FIND_BED_OFFSET_AND_SKEW_LINE1		"Suche Bett Kalibrierpunkt"
#define MSG_FIND_BED_OFFSET_AND_SKEW_LINE2		" von 4"
#define MSG_IMPROVE_BED_OFFSET_AND_SKEW_LINE1	"Genauigkeit verbessern bei Kalibrierpunkt"
#define MSG_IMPROVE_BED_OFFSET_AND_SKEW_LINE2	" von 9"
#define MSG_MEASURE_BED_REFERENCE_HEIGHT_LINE1	"Messen der Referenzhoehe des Kalibrierpunktes"
#define MSG_MEASURE_BED_REFERENCE_HEIGHT_LINE2	" von 9"
#define MSG_FIND_BED_OFFSET_AND_SKEW_ITERATION	"Wiederholung "

#define MSG_BED_SKEW_OFFSET_DETECTION_POINT_NOT_FOUND			"XYZ-Kalibrierung fehlgeschlagen. Bett-Kalibrierpunkt nicht gefunden."
#define MSG_BED_SKEW_OFFSET_DETECTION_FITTING_FAILED			"XYZ-Kalibrierung fehlgeschlagen. Bitte schauen Sie in das Handbuch."
#define MSG_BED_SKEW_OFFSET_DETECTION_PERFECT					"XYZ-Kalibrierung ok. X/Y-Achsen sind senkrecht zueinander. Glueckwunsch!"
#define MSG_BED_SKEW_OFFSET_DETECTION_SKEW_MILD					"XYZ-Kalibrierung ok. X/Y-Achsen sind etwas schief. Schiefheit wird automatisch korrigiert. Gut gemacht!"
#define MSG_BED_SKEW_OFFSET_DETECTION_SKEW_EXTREME				"XYZ-Kalibrierung ok. X/Y-Achsen sind sehr schief. Schiefheit wird automatisch korrigiert."
#define MSG_BED_SKEW_OFFSET_DETECTION_FAILED_FRONT_LEFT_FAR		"XYZ-Kalibrierung fehlgeschlagen. Linker voderer Kalibrierpunkt nicht erreichbar."
#define MSG_BED_SKEW_OFFSET_DETECTION_FAILED_FRONT_RIGHT_FAR	"XYZ-Kalibrierung fehlgeschlagen. Rechter vorderer Kalibrierpunkt nicht erreichbar."
#define MSG_BED_SKEW_OFFSET_DETECTION_FAILED_FRONT_BOTH_FAR		"XYZ-Kalibrierung fehlgeschlagen. Vordere Kalibrierpunkte nicht erreichbar."
#define MSG_BED_SKEW_OFFSET_DETECTION_WARNING_FRONT_LEFT_FAR	"XYZ-Kalibrierung ungenau. Linker vorderer Kalibrierpunkt nicht erreichbar."
#define MSG_BED_SKEW_OFFSET_DETECTION_WARNING_FRONT_RIGHT_FAR	"XYZ-Kalibrierung ungenau. Rechter vorderer Kalibrierpunkt nicht erreichbar."
#define MSG_BED_SKEW_OFFSET_DETECTION_WARNING_FRONT_BOTH_FAR	"XYZ-Kalibrierung ungenau. Vordere Kalibrierpunkte nicht erreichbar."

#define MSG_BED_LEVELING_FAILED_POINT_LOW						"Bett-Nivellierung fehlgeschlagen. Sensor wurde nicht ausgeloest. Schmutzige Buse? Warte auf Reset."
#define MSG_BED_LEVELING_FAILED_POINT_HIGH						"Bett-Nivellierung fehlgeschlagen. Sensor wurde zu hoch ausgeloest. Warte auf Reset."
#define MSG_BED_LEVELING_FAILED_PROBE_DISCONNECTED				"Bett-Nivellierung fehlgeschlagen. Sensor nicht angeschlossen oder Kabel defekt. Warte auf Reset."

#define MSG_NEW_FIRMWARE_AVAILABLE								"Neue Firmware Version verfuegbar:"
#define MSG_NEW_FIRMWARE_PLEASE_UPGRADE							"Bitte aktualisieren."

#define MSG_FOLLOW_CALIBRATION_FLOW								"Der Drucker wurde noch nicht kalibriert. Bitte folgen Sie dem Handbuch, Kapitel First steps, Abschnitt Calibration flow."
#define MSG_BABYSTEP_Z_NOT_SET									"Der Abstand zwischen der Spitze der Buse und der Druckoberflaeche / Bett ist noch nicht eingestellt. Bitte folgen Sie dem Handbuch, First steps, Abschnitt First layer calibration."

#define MSG_FILAMENT_LOADING_T0				"Filament in extruder 1 einlegen. Klicken wenn fertig."
#define MSG_FILAMENT_LOADING_T1				"Filament in extruder 2 einlegen. Klicken wenn fertig."
#define MSG_FILAMENT_LOADING_T2				"Filament in extruder 3 einlegen. Klicken wenn fertig."
#define MSG_FILAMENT_LOADING_T3				"Filament in extruder 4 einlegen. Klicken wenn fertig."
#define MSG_CHANGE_EXTR						"Wechsel extruder"

#define MSG_FIL_ADJUSTING					"Einstellen Filament. Bitte warten."
#define MSG_CONFIRM_NOZZLE_CLEAN_FIL_ADJ	"Filamente sind jetzt eingestellt. Bitte reinigen Sie die Buse zur Kalibrierung. Klicken wenn sauber."
#define MSG_STACK_ERROR						"Error - EEPROM wurde ueberschrieben"																																		   

#define MSG_CALIBRATE_E						"Kalibriere E"
#define MSG_RESET_CALIBRATE_E				"Reset E Cal."
#define MSG_E_CAL_KNOB						"Knopf drehen bis die Filamentmarkierung erreicht ist. Klicken wenn fertig."

//#define MSG_FARM_CARD_MENU				"Farm mode print"

#define MSG_MARK_FIL						"Filament 100mm vom Extrudergehaeuse markieren. Klicken wenn Fertig."
#define MSG_CLEAN_NOZZLE_E					"E-Kalibrierung beendet. Bitte reinigen Sie die Buse. Klicken wenn fertig."
#define MSG_WAITING_TEMP					"Warten auf Abkuehlung von Buse und Bett."

#define MSG_FILAMENT_CLEAN					"Ist Farbe rein?"
#define MSG_UNLOADING_FILAMENT				"Filament auswerfen"
#define MSG_PAPER							"Lege waehrend der Kalibrierung der ersten 4 Punkte ein Blatt Papier unter die Buse. Wenn die Buse das Papier bewegt, Drucker sofort ausschalten!"

#define MSG_BED_CORRECTION_MENU				"Bett level korrekt"


#define MSG_BED_CORRECTION_MID_LEFT				"Mi.Links  [um]"
#define MSG_BED_CORRECTION_MID_RIGHT			"Mi.Rechts [um]"
#define MSG_BED_CORRECTION_FRONT_CENTR			"Ztr.Vorne [um]"
#define MSG_BED_CORRECTION_REAR_CENTR			"Ztr.Hinten[um]"

#define MSG_BED_CORRECTION_RESET			"Zuruecksetzen"

#define MSG_MESH_BED_LEVELING				"Mesh Bed Leveling"
#define MSG_MENU_CALIBRATION				"Kalibrierung"

#define MSG_TOSHIBA_FLASH_AIR_COMPATIBILITY_OFF	"SD Karte [normal]"
#define MSG_TOSHIBA_FLASH_AIR_COMPATIBILITY_ON	"SD Karte [FlashAir]"
#define MSG_PRINTER_DISCONNECTED			"Drucker getrent"
#define MSG_FINISHING_MOVEMENTS				"Bewegungen beenden"
#define MSG_PRINT_PAUSED					"Druck pausiert"
#define MSG_RESUMING_PRINT					"Druck fortsetzen"
#define MSG_PID_EXTRUDER					"PID Kalibrierung"
#define MSG_SET_TEMPERATURE					"Temp.einstellen"
#define MSG_PID_FINISHED					"PID Kal. fertig     "
#define MSG_PID_RUNNING						"PID Kal.     "

#define MSG_CALIBRATE_PINDA					"PINDA Temp. Kal."
#define MSG_CALIBRATION_PINDA_MENU			"PINDA Temp. Kal."
#define MSG_PINDA_NOT_CALIBRATED			"PINDA Temperatur Kalibrierung wurde noch nicht ausgefuehrt"
#define MSG_PINDA_PREHEAT					"PINDA erwaermen"
#define MSG_TEMP_CALIBRATION				"PINDA Temp.Kal.     "
#define MSG_TEMP_CALIBRATION_DONE			"Die PINDA Temperaturkalibrierung ist beendet. Klicke um fortzufahren."
#define MSG_TEMP_CALIBRATION_ON				"PINDA T.Kal. [ON]"
#define MSG_TEMP_CALIBRATION_OFF			"PINDA T.Kal.[OFF]"

#define MSG_PREPARE_FILAMENT				"Filam. bereithalten"
#define MSG_ALL								"Alle"
#define MSG_USED							"Benutzt beim Druck"
#define MSG_CURRENT							"Aktuelles"
#define MSG_CHOOSE_EXTRUDER					"Waehlen Sie Extruder"
#define MSG_EXTRUDER						"Extruder"
#define MSG_EXTRUDER_1						"Extruder 1"
#define MSG_EXTRUDER_2						"Extruder 2"
#define MSG_EXTRUDER_3						"Extruder 3"
#define MSG_EXTRUDER_4						"Extruder 4"
#define MSG_DATE							"Datum:"
#define MSG_XYZ_DETAILS						"XYZ Kal. Details"
#define	MSG_Y_DISTANCE_FROM_MIN				"Y Entfernung von min"
#define	MSG_LEFT							"Links:"
#define MSG_CENTER							"Mitte:"
#define MSG_RIGHT							"Rechts:"
#define MSG_MEASURED_SKEW					"Symmetrie:"
#define MSG_SLIGHT_SKEW						"Geringe Asym.:"
#define MSG_SEVERE_SKEW						"Schwere Asym.:"
#define MSG_DEFAULT_SETTINGS_LOADED			"Standardeinstellungen geladen"
#define MSG_SORT_TIME						"Sort:     [Zeit]"
#define MSG_SORT_ALPHA						"Sort: [Alphabet]"
#define MSG_SORT_NONE						"Sort:    [Keine]"
#define MSG_SORTING							"Sortiere Dateien"
#define MSG_FILE_INCOMPLETE					"Bestand unvollstaedig. Trotzdem weiter machen?"
#define MSG_WIZARD							"Assistent"
#define	MSG_WIZARD_LANGUAGE					"Bitte Sprache waehlen"
#define	MSG_WIZARD_WELCOME					"Hallo, ich bin Dein Original Prusa i3 Drucker. Sollen wir mit dem Setup-Prozess beginnen?"
#define	MSG_WIZARD_QUIT						"Du kannst den Assistenten immer aus Kalibrierung -> Assistent wider aufnehmen."
#define MSG_WIZARD_SELFTEST					"Zuerst werden wir den Selbsttest durchfuehren um haeufige Montageprobleme zu ueberpruefen."
#define MSG_WIZARD_CALIBRATION_FAILED		"Bitte ueberpruefe unser Handbuch und behebe das Problem. Fahre dann mit dem Assistenten fort, indem Du den Drucker neu startest."
#define MSG_WIZARD_XYZ_CAL					"Starte jetzt die XYZ-Kalibrierung. Es wird ca. 12 min. dauern."
#define MSG_WIZARD_FILAMENT_LOADED		"Filament geladen?"
#define MSG_WIZARD_Z_CAL					"Starte jetzt die Z-Kalibrierung."
#define MSG_WIZARD_WILL_PREHEAT				"Waerme die Buse fuer PLA vor."
#define MSG_WIZARD_HEATING					"Vorwaermen der Buse. Bitte warten."
#define MSG_WIZARD_V2_CAL					"Starte mit der Kalibrierung zwischen der Buse und Bett."
#define MSG_WIZARD_V2_CAL_2					"Starte die Kal.-Linie zu drucken, bitte drehe am Knopf bis Du die optimale Hoehe erreichst. Schaue im Handbuch unter Calibration nach."
#define MSG_V2_CALIBRATION					"Erste Layer Kal."
#define MSG_WIZARD_DONE						"Fertig. Happy printing!"
#define MSG_WIZARD_LOAD_FILAMENT			"Fuehre PLA Filament in den Extruder und drueck den Knopf um dies zu laden."
#define MSG_WIZARD_RERUN					"Starten vom Assistenten loescht die aktuelle Kalibrierung und beginnt von vorne. Fortsetzen?"
#define MSG_WIZARD_REPEAT_V2_CAL					"Willst Du den letzten Schritt widerholen um den Abstand zwischen Buse und Bett erneut einzustellen?"
#define MSG_WIZARD_CLEAN_HEATBED					"Bitte reinige das Bett und druecke den Knopf."
#define MSG_WIZARD_PLA_FILAMENT					"Ist es PLA Filament?"
#define MSG_WIZARD_INSERT_CORRECT_FILAMENT			"Bitte lade PLA Filament und starte den Drucker neu um den Assistenten fortzusetzen."
#define MSG_PLA_FILAMENT_LOADED				"Ist PLA Filament geladen?"
#define MSG_PLEASE_LOAD_PLA					"Bitte lade erst PLA Filament."
#define MSG_FILE_CNT	"Einige Dateien werden nicht sortiert, da das max. 100 Dateien pro Ordner ist."
*/