// These are the system messages, which shall always be in English.

+define MSG_Enqueing                        "enqueing \""
+define MSG_POWERUP                         "PowerUp"
define MSG_EXTERNAL_RESET                  " External Reset"
define MSG_BROWNOUT_RESET                  " Brown out Reset"
define MSG_WATCHDOG_RESET                  " Watchdog Reset"
define MSG_SOFTWARE_RESET                  " Software Reset"
define MSG_AUTHOR                          " | Author: "
+define MSG_CONFIGURATION_VER               " Last Updated: "
+define MSG_FREE_MEMORY                     " Free Memory: "
+define MSG_PLANNER_BUFFER_BYTES            "  PlannerBufferBytes: "
+define MSG_OK                              "ok"
define MSG_FILE_SAVED                      "Done saving file."
define MSG_ERR_LINE_NO                     "Line Number is not Last Line Number+1, Last Line: "
+define MSG_ERR_CHECKSUM_MISMATCH           "checksum mismatch, Last Line: "
+define MSG_ERR_NO_CHECKSUM                 "No Checksum with line number, Last Line: "
define MSG_ERR_NO_LINENUMBER_WITH_CHECKSUM "No Line Number with checksum, Last Line: "
define MSG_FILE_PRINTED                    "Done printing file"
+define MSG_BEGIN_FILE_LIST                 "Begin file list"
+define MSG_END_FILE_LIST                   "End file list"
+define MSG_M104_INVALID_EXTRUDER           "M104 Invalid extruder "
+define MSG_M105_INVALID_EXTRUDER           "M105 Invalid extruder "
+define MSG_M200_INVALID_EXTRUDER           "M200 Invalid extruder "
+define MSG_M218_INVALID_EXTRUDER           "M218 Invalid extruder "
+define MSG_M221_INVALID_EXTRUDER           "M221 Invalid extruder "
+define MSG_ERR_NO_THERMISTORS              "No thermistors - no temperature"
+define MSG_M109_INVALID_EXTRUDER           "M109 Invalid extruder "
+define MSG_M115_REPORT                     "FIRMWARE_NAME:Marlin V1.0.2; Sprinter/grbl mashup for gen6 FIRMWARE_URL:" FIRMWARE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" CUSTOM_MENDEL_NAME " EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) " UUID:" MACHINE_UUID "\n"
define MSG_COUNT_X                         " Count X: "
+define MSG_ERR_KILLED                      "Printer halted. kill() called!"
+define MSG_ERR_STOPPED                     "Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)"
+define MSG_RESEND                          "Resend: "
define MSG_UNKNOWN_COMMAND                 "Unknown command: \""
define MSG_ACTIVE_EXTRUDER                 "Active Extruder: "
define MSG_INVALID_EXTRUDER                "Invalid extruder"

define MSG_X_MIN                           "x_min: "
define MSG_X_MAX                           "x_max: "
define MSG_Y_MIN                           "y_min: "
define MSG_Y_MAX                           "y_max: "
define MSG_Z_MIN                           "z_min: "
define MSG_Z_MAX                           "z_max: "

+define MSG_M119_REPORT                     "Reporting endstop status"
+define MSG_ENDSTOP_HIT                     "TRIGGERED"
+define MSG_ENDSTOP_OPEN                    "open"
+define MSG_HOTEND_OFFSET                   "Hotend offsets:"
+define MSG_SD_CANT_OPEN_SUBDIR             "Cannot open subdir"
+define MSG_SD_INIT_FAIL                    "SD init fail"
+define MSG_SD_VOL_INIT_FAIL                "volume.init failed"
+define MSG_SD_OPENROOT_FAIL                "openRoot failed"
+define MSG_SD_CARD_OK                      "SD card ok"
+define MSG_SD_WORKDIR_FAIL                 "workDir open failed"
+define MSG_SD_OPEN_FILE_FAIL               "open failed, File: "
+define MSG_SD_FILE_OPENED                  "File opened: "
define MSG_SD_SIZE                         " Size: "
+define MSG_SD_FILE_SELECTED                "File selected"
+define MSG_SD_WRITE_TO_FILE                "Writing to file: "
+define MSG_SD_PRINTING_BYTE                "SD printing byte "
+define MSG_SD_NOT_PRINTING                 "Not SD printing"
+define MSG_SD_ERR_WRITE_TO_FILE            "error writing to file"
+define MSG_SD_CANT_ENTER_SUBDIR            "Cannot enter subdir: "
+define MSG_STEPPER_TOO_HIGH                "Steprate too high: "
+define MSG_ENDSTOPS_HIT                    "endstops hit: "
+define MSG_ERR_COLD_EXTRUDE_STOP           " cold extrusion prevented"
define MSG_ERR_LONG_EXTRUDE_STOP           " too long extrusion prevented"
+define MSG_BABYSTEPPING_X                  "Babystepping X"
+define MSG_BABYSTEPPING_Y                  "Babystepping Y"
+define MSG_SERIAL_ERROR_MENU_STRUCTURE     "Error in menu structure"
+define MSG_SET_HOME_OFFSETS                "Set home offsets"
+define MSG_SET_ORIGIN                      "Set origin"
define MSG_ON                              "On "
define MSG_OFF                             "Off"

+define MSG_VMIN                            "Vmin"
+define MSG_VTRAV_MIN                       "VTrav min"
+define MSG_AMAX                            "Amax "
+define MSG_A_RETRACT                       "A-retract"
+define MSG_MOVE_01MM                       "Move 0.1mm"
+define MSG_MOVE_1MM                        "Move 1mm"
+define MSG_MOVE_10MM                       "Move 10mm"


+define MSG_NOZZLE1                         "Nozzle2"
+define MSG_NOZZLE2                         "Nozzle3"
+define MSG_FLOW0                           "Flow 0"
+define MSG_FLOW1                           "Flow 1"
+define MSG_FLOW2                           "Flow 2"
+define MSG_CONTROL                         "Control"
+define MSG_MIN                             " \002 Min"
+define MSG_MAX                             " \002 Max"
+define MSG_FACTOR                          " \002 Fact"
+define MSG_MOTION                          "Motion"
+define MSG_VOLUMETRIC                      "Filament"
+define MSG_VOLUMETRIC_ENABLED		        "E in mm3"
+define MSG_STORE_EPROM                     "Store memory"
+define MSG_LOAD_EPROM                      "Load memory"
+define MSG_RESTORE_FAILSAFE                "Restore failsafe"
+define MSG_REFRESH                         "\xF8" "Refresh"

+define MSG_INIT_SDCARD                     "Init. SD card"
+define MSG_CNG_SDCARD                      "Change SD card"
define MSG_ZPROBE_OUT                      "Z probe out. bed"
define MSG_POSITION_UNKNOWN                "Home X/Y before Z"
define MSG_ZPROBE_ZOFFSET                  "Z Offset"
+define MSG_BABYSTEP_X                      "Babystep X"
+define MSG_BABYSTEP_Y                      "Babystep Y"
+define MSG_RECTRACT                        "Rectract"
