/**
 * French
 *
 * LCD Menu Messages
 * Please note these are limited to 17 characters!
 */

#define(length=20) WELCOME_MSG              CUSTOM_MENDEL_NAME " prete."
#define MSG_SD_INSERTED						"Carte inseree"
#define MSG_SD_REMOVED						"Carte retiree "
#define MSG_MAIN							"Menu principal"
#define MSG_DISABLE_STEPPERS				"Arreter moteurs"
#define MSG_AUTO_HOME						"Origine auto."
#define MSG_SET_HOME_OFFSETS				"Regl. decal. origine"
#define MSG_SET_ORIGIN						"Definir origine"
#define MSG_COOLDOWN						"Refroidir"
#define MSG_SWITCH_PS_ON					"Allumer alim."
#define MSG_SWITCH_PS_OFF					"Eteindre alim."
#define MSG_MOVE_AXIS						"Deplacer un axe"
#define MSG_MOVE_X							"Deplacer X"
#define MSG_MOVE_Y							"Deplacer Y"
#define MSG_MOVE_Z							"Deplacer Z"
#define MSG_MOVE_E							"Extruder"
#define MSG_SPEED							"Vitesse"
#define MSG_NOZZLE							"Buse"
#define MSG_NOZZLE1							"Buse2"
#define MSG_NOZZLE2							"Buse3"
#define MSG_BED								"Plateau"
#define MSG_FAN_SPEED						"Vitesse ventil"
#define MSG_FLOW							"Flux"
#define MSG_FLOW0							"Flux 0"
#define MSG_FLOW1							"Flux 1"
#define MSG_FLOW2							"Flux 2"
#define MSG_CONTROL							"Controler"
#define MSG_MIN								" \002 Min"
#define MSG_MAX								" \002 Max"
#define MSG_FACTOR							" \002 Fact"
#define MSG_TEMPERATURE						"Temperature"
#define MSG_MOTION							"Mouvement"
#define MSG_VOLUMETRIC						"Filament"
#define MSG_VOLUMETRIC_ENABLED				"E en mm3"
#define MSG_STORE_EPROM						"Sauver config"
#define MSG_LOAD_EPROM						"Lire config"
#define MSG_RESTORE_FAILSAFE				"Restaurer defauts"
#define MSG_REFRESH                         "\xF8" "Actualiser"
#define MSG_WATCH                           "Ecran info"
#define MSG_TUNE							"Regler"
#define MSG_PAUSE_PRINT						"Suspendre impr."
#define MSG_RESUME_PRINT					"Reprendre impr."
#define MSG_STOP_PRINT						"Arreter impr."
#define MSG_CARD_MENU						"Impr. depuis SD"
#define MSG_NO_CARD							"Pas de carte"
#define MSG_DWELL							"Repos..."
#define MSG_USERWAIT						"Atten. de l'util."
#define MSG_RESUMING						"Reprise impr."
#define MSG_PRINT_ABORTED					"Impr. Annulee"
#define MSG_NO_MOVE							"Moteurs bloques."
#define MSG_KILLED							"INCIDENT."
#define MSG_STOPPED							"INTERRUPTION."
#define MSG_FILAMENTCHANGE					"Changer filament"
#define MSG_INIT_SDCARD						"Init. la carte SD"
#define MSG_CNG_SDCARD						"Changer de carte"
#define MSG_BABYSTEP_X						"Babystep X"
#define MSG_BABYSTEP_Y						"Babystep Y"
#define MSG_BABYSTEP_Z						"Ajuster axe Z"
#define MSG_ADJUSTZ							"Reglage auto Z?"
#define MSG_PICK_Z							"Choisir impression"

#define MSG_SETTINGS						"Reglage"
#define MSG_PREHEAT							"Prechauffage"
#define(length=17) MSG_UNLOAD_FILAMENT		"Ejecter filam."
#define(length=17) MSG_LOAD_FILAMENT		"Charger filament"
#define(length=17) MSG_LOAD_FILAMENT_1		"Charger filam. 1"
#define(length=17) MSG_LOAD_FILAMENT_2		"Charger filam. 2"
#define(length=17) MSG_LOAD_FILAMENT_3		"Charger filam. 3"
#define(length=17) MSG_LOAD_FILAMENT_4		"Charger filam. 4"
#define(length=17) MSG_UNLOAD_FILAMENT_1	"Ejecter filam. 1"
#define(length=17) MSG_UNLOAD_FILAMENT_2	"Ejecter filam. 2"
#define(length=17) MSG_UNLOAD_FILAMENT_3	"Ejecter filam. 3"
#define(length=17) MSG_UNLOAD_FILAMENT_4	"Ejecter filam. 4"
#define MSG_UNLOAD_ALL						"Ejecter tout"
#define MSG_LOAD_ALL						"Charger tout"


#define MSG_RECTRACT                        "Retraction"
#define MSG_ERROR                        	"ERREUR:"
#define(length=20) MSG_PREHEAT_NOZZLE       "Prechauff. buse!"
#define MSG_SUPPORT 						"Support"
#define(length=20) MSG_CORRECTLY			"Changement correct?"
#define MSG_YES								"Oui"
#define MSG_NO								"Non"
#define(length=19) MSG_NOT_LOADED 			"Filament non charge"
#define MSG_NOT_COLOR 						"Couleurs melange"
#define(length=20) MSG_LOADING_FILAMENT		"Chargement filament"
#define(length=20) MSG_PLEASE_WAIT			"Attendre svp"
#define MSG_LOADING_COLOR					"Chargem. couleur"
#define MSG_CHANGE_SUCCESS					"Changem. correct!"
#define(length=20) MSG_PRESS				"et presser bouton"
#define(length=20) MSG_INSERT_FILAMENT		"Inserer filament"
#define(length=20) MSG_CHANGING_FILAMENT	"Changement filament!"

#define MSG_SILENT_MODE_ON					"Mode [silencieux]"
#define MSG_SILENT_MODE_OFF					"Mode  [puissance]"
#define MSG_AUTO_MODE_ON					"Mode[automatique]"
#define(length=20) MSG_REBOOT				"Redemarrer imprim."
//#define(length=20) MSG_TAKE_EFFECT			" pour prendre effet"

#define MSG_Enqueing                        "mise en file "
#define MSG_POWERUP                         "Allumage"
#define MSG_CONFIGURATION_VER               "Mise a jour: "
#define MSG_FREE_MEMORY                     "Memoire libre: "
#define MSG_PLANNER_BUFFER_BYTES            "PlannerBufferBytes: "
#define MSG_OK                              "Ok"
#define MSG_ERR_CHECKSUM_MISMATCH           "Mauvais checksum, derniere ligne: "
#define MSG_ERR_NO_CHECKSUM                 "Absence Checksum avec numero ligne, derniere ligne: "
#define MSG_BEGIN_FILE_LIST                 "Debut liste fichiers"
#define MSG_END_FILE_LIST                   "Fin liste fichiers"
#define MSG_M104_INVALID_EXTRUDER           "M104 Extrudeur inval."
#define MSG_M105_INVALID_EXTRUDER           "M105 Extrudeur inval."
#define MSG_M200_INVALID_EXTRUDER           "M200 Extrudeur inval."
#define MSG_M218_INVALID_EXTRUDER           "M218 Extrudeur inval."
#define MSG_M221_INVALID_EXTRUDER           "M221 Extrudeur inval."
#define MSG_ERR_NO_THERMISTORS              "Pas de thermistances - pas de temperature"
#define MSG_M109_INVALID_EXTRUDER           "M109 Extrudeur inval."
#define MSG_HEATING                         "Prechauffage"
#define(length=20) MSG_HEATING_COMPLETE     "Prechauffage OK"
#define MSG_BED_HEATING                     "Prechauff. Plat."
#define MSG_BED_DONE                        "Plateau chaud"
#define MSG_M115_REPORT                     "FIRMWARE_NAME:Marlin V1.0.2; Sprinter/grbl adaptation pour gen6 FIRMWARE_URL:" FIRMWARE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" CUSTOM_MENDEL_NAME " EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) " UUID:" MACHINE_UUID "\n"
#define MSG_ERR_KILLED                      "Imprimante arretee. appel kill()!"
#define MSG_ERR_STOPPED						"Imprimante arretee en raison d'erreurs. Corrigez l'erreur et utilisez M999 pour redemarrer. (La temperature est reinitialisee, reglez-la apres le redemarrage)"
#define MSG_RESEND                          "Re-envoyer: "
#define MSG_M119_REPORT                     "Envoi etat butee"
#define MSG_ENDSTOP_HIT                     "CONTACT"
#define MSG_ENDSTOP_OPEN                    "ouvert"

#define MSG_SD_CANT_OPEN_SUBDIR             "Erreur ouverture Rep"
#define MSG_SD_INIT_FAIL                    "Erreur init SD"
#define MSG_SD_VOL_INIT_FAIL                "Erreur volume.init"
#define MSG_SD_OPENROOT_FAIL                "Erreur openRoot"
#define MSG_SD_CARD_OK                      "SD card ok"
#define MSG_SD_WORKDIR_FAIL                 "erreur access workDir"
#define MSG_SD_OPEN_FILE_FAIL               "Erreur fichier: "
#define MSG_SD_FILE_OPENED                  "Fichier ouvert: "
#define MSG_SD_FILE_SELECTED                "Fichier choisi"
#define MSG_SD_WRITE_TO_FILE                "Ecriture fichier: "
#define MSG_SD_PRINTING_BYTE                "SD printing byte "
#define MSG_SD_NOT_PRINTING                 "Pas d'impression SD"
#define MSG_SD_ERR_WRITE_TO_FILE            "Erreur ecrit. fichier"
#define MSG_SD_CANT_ENTER_SUBDIR            "Erreur acces Rep"

#define MSG_STEPPER_TOO_HIGH                "Pas moteur trop haut: "
#define MSG_ENDSTOPS_HIT                    "contact butee: "
#define MSG_ERR_COLD_EXTRUDE_STOP           "Stop, extrusion a froid"
#define MSG_BABYSTEPPING_X                  "Babystepping X"
#define MSG_BABYSTEPPING_Y                  "Babystepping Y"
#define MSG_BABYSTEPPING_Z                  "Adjusting Z"
#define MSG_SERIAL_ERROR_MENU_STRUCTURE     "Erreur structure menu"

#define MSG_LANGUAGE_NAME					"Francais"
#define MSG_LANGUAGE_SELECT					"Selection langue"
#define MSG_PRUSA3D							"prusa3d.com"
#define MSG_PRUSA3D_FORUM					"forum.prusa3d.com"
#define MSG_PRUSA3D_HOWTO					"howto.prusa3d.com"

#define MSG_SELFTEST_ERROR					"Error diagnostic!"
#define MSG_SELFTEST_PLEASECHECK			"Verifier SVP:"	
#define MSG_SELFTEST_NOTCONNECTED			"Non connecte"
#define MSG_SELFTEST_HEATERTHERMISTOR		"Chauf./Thermist."
#define MSG_SELFTEST_BEDHEATER				"Plateau/Chauf."
#define MSG_SELFTEST_WIRINGERROR			"Erreur cablage"
#define MSG_SELFTEST_ENDSTOPS				"Butees"
#define MSG_SELFTEST_MOTOR					"Moteur"
#define MSG_SELFTEST_ENDSTOP				"Butee"
#define(length=20,lines=1) MSG_SELFTEST_ENDSTOP_NOTHIT			"Butee non atteinte"
#define MSG_SELFTEST_OK						"Diagnostic OK"
#define(length=20,lines=1) MSG_LOOSE_PULLEY	"Poulie desseree"

#define(length=20) MSG_SELFTEST_FAN			"Test ventilateurs"
#define(length=20) MSG_SELFTEST_COOLING_FAN		"Ventilateur avant?";
#define(length=20) MSG_SELFTEST_EXTRUDER_FAN	"Ventilateur gauche?"
#define MSG_SELFTEST_FAN_YES				"En rotation"
#define MSG_SELFTEST_FAN_NO					"Immobile"

#define(length=20) MSG_STATS_TOTALFILAMENT	"Total filament :"
#define(length=20) MSG_STATS_TOTALPRINTTIME "Total print time :"
#define(length=20) MSG_STATS_FILAMENTUSED	"Filament used:  "
#define(length=20) MSG_STATS_PRINTTIME		"Print time:  "
#define(length=20) MSG_SELFTEST_START				"Debut diagnostic "
#define(length=20) MSG_SELFTEST_CHECK_ENDSTOPS		"Test butees      "
#define(length=20) MSG_SELFTEST_CHECK_HOTEND		"Test hotend  "  
#define(length=20) MSG_SELFTEST_CHECK_X				"Test axe X       "
#define(length=20) MSG_SELFTEST_CHECK_Y				"Test axe Y axis  "
#define(length=20) MSG_SELFTEST_CHECK_Z				"Test axe Z axis  "
#define(length=20) MSG_SELFTEST_CHECK_BED			"Test Chauf. Plat."
#define(length=20) MSG_SELFTEST_CHECK_ALLCORRECT	"Diagnostic reussi"
#define MSG_SELFTEST						"Diagnostic       "
#define(length=20) MSG_SELFTEST_FAILED		"Echec Diagnostic "
#define MSG_STATISTICS						"Statistiques"
#define MSG_USB_PRINTING					"Impression USB "
#define MSG_HOMEYZ                          "Calibration Z"
#define MSG_HOMEYZ_PROGRESS                 "Calib. Z en cours"
#define MSG_HOMEYZ_DONE		                "Calibration done"

#define(length=17,lines=1) MSG_SHOW_END_STOPS	"Montre butees "
#define MSG_CALIBRATE_BED					"Calibration XYZ"
#define MSG_CALIBRATE_BED_RESET				"RAZ XYZ calibr."

#define(length=20,lines=8) MSG_MOVE_CARRIAGE_TO_THE_TOP 	"Calibration XYZ. Tourner le bouton pour monter axe Z jusque la butee. Presser bouton pour poursuivre."
#define(length=20,lines=8) MSG_MOVE_CARRIAGE_TO_THE_TOP_Z 	"Calibration Z. Tourner le bouton pour monter axe Z jusque la butee. Presser bouton pour poursuivre."

#define(length=20,lines=8) MSG_CONFIRM_NOZZLE_CLEAN			"Nettoyer la buse avant la calibration. Presser bouton pour poursuivre."
#define(length=20,lines=2) MSG_CONFIRM_CARRIAGE_AT_THE_TOP	"Axe Z droit et gauche tout en haut?"

#define(length=60) MSG_FIND_BED_OFFSET_AND_SKEW_LINE1		"Recherche points calibration plateau"
#define(length=14) MSG_FIND_BED_OFFSET_AND_SKEW_LINE2		" sur 4"
#define(length=60) MSG_IMPROVE_BED_OFFSET_AND_SKEW_LINE1	"Affinage points calibration plateau"
#define(length=14) MSG_IMPROVE_BED_OFFSET_AND_SKEW_LINE2	" sur 9"
#define(length=60) MSG_MEASURE_BED_REFERENCE_HEIGHT_LINE1	"Mesure hauteur de reference points calibration"
#define(length=14) MSG_MEASURE_BED_REFERENCE_HEIGHT_LINE2	" sur 9"
#define(length=20) MSG_FIND_BED_OFFSET_AND_SKEW_ITERATION	"Iteration "

#define(length=20,lines=8) MSG_BED_SKEW_OFFSET_DETECTION_POINT_NOT_FOUND			"Echec calibration XYZ. Point de calibration non trouve."
#define(length=20,lines=8) MSG_BED_SKEW_OFFSET_DETECTION_FITTING_FAILED				"Echec calibration XYZ. SVP consulter le manuel."
#define(length=20,lines=8) MSG_BED_SKEW_OFFSET_DETECTION_PERFECT					"Calibration XYZ parfaite. Axes X/Y perpendiculaires. Felicitations!"
#define(length=20,lines=8) MSG_BED_SKEW_OFFSET_DETECTION_SKEW_MILD					"Calibration XYZ correcte. Axes X/Y faiblement obliques. Bien joue!"
#define(length=20,lines=8) MSG_BED_SKEW_OFFSET_DETECTION_SKEW_EXTREME				"Calibration XYZ ecceptable. Les axes X/Y obliques seront compenses automatiquement."
#define(length=20,lines=8) MSG_BED_SKEW_OFFSET_DETECTION_FAILED_FRONT_LEFT_FAR		"Echec calibration XYZ. Point calibration avant gauche introuvable."
#define(length=20,lines=8) MSG_BED_SKEW_OFFSET_DETECTION_FAILED_FRONT_RIGHT_FAR		"Echec calibration XYZ. Point calibration avant droit introuvable."
#define(length=20,lines=8) MSG_BED_SKEW_OFFSET_DETECTION_FAILED_FRONT_BOTH_FAR		"Echec calibration XYZ. 2 Points calibration avant introuvables."
#define(length=20,lines=8) MSG_BED_SKEW_OFFSET_DETECTION_WARNING_FRONT_LEFT_FAR		"Calibration XYZ defaillante. Point calibration avant gauche introuvable."
#define(length=20,lines=8) MSG_BED_SKEW_OFFSET_DETECTION_WARNING_FRONT_RIGHT_FAR	"Calibration XYZ defaillante. Point calibration avant droit introuvable."
#define(length=20,lines=8) MSG_BED_SKEW_OFFSET_DETECTION_WARNING_FRONT_BOTH_FAR		"Calibration XYZ defaillante. 2 Points calibration avant introuvables."

#define(length=20,lines=6) MSG_BED_LEVELING_FAILED_POINT_LOW			"Echec mesure hauteur plateau. Debris sur buse ? Attente de Reset."
#define(length=20,lines=6) MSG_BED_LEVELING_FAILED_POINT_HIGH			"Echec mesure hauteur plateau. Declenchement senseur trop haut. Attente de Reset."
#define(length=20,lines=6) MSG_BED_LEVELING_FAILED_PROBE_DISCONNECTED	"Echec mesure hauteur plateau. Senseur deconnecte ou cable endommage. Attente de Reset."

#define(length=20,lines=2) MSG_NEW_FIRMWARE_AVAILABLE		"Nouveau firmware disponible:"
#define(length=20) MSG_NEW_FIRMWARE_PLEASE_UPGRADE			"Mettre a jour SVP."

#define(length=20,lines=8) MSG_FOLLOW_CALIBRATION_FLOW		"Imprimante non calibree. SVP Consulter le manuel, chapitre premiers pas, section gestion de la calibration."
#define(length=20,lines=12) MSG_BABYSTEP_Z_NOT_SET			"Distance entre la pointe de la buse pas encore mesuree. SVP Consulter le manuel, chapitre premiers pas, section mesure de la premiere couche."

#define(length=20, lines=4) MSG_FILAMENT_LOADING_T0			"Inserer filament dans extrudeur 1, puis presser bouton."
#define(length=20, lines=4) MSG_FILAMENT_LOADING_T1			"Inserer filament dans extrudeur 2, puis presser bouton."
#define(length=20, lines=4) MSG_FILAMENT_LOADING_T2			"Inserer filament dans extrudeur 3, puis presser bouton."
#define(length=20, lines=4) MSG_FILAMENT_LOADING_T3			"Inserer filament dans extrudeur 4, puis presser bouton."
#define(length=20, lines=1) MSG_CHANGE_EXTR					"Changer extrudeur"

#define(length=20, lines=4) MSG_FIL_ADJUSTING				"Ajustement filaments. Attendre SVP."
#define(length=20,lines=8) MSG_CONFIRM_NOZZLE_CLEAN_FIL_ADJ	"Filaments ajustes. Merci de nettoyer la buse pour la calibration. Cliquez quand Ok."
#define(length=20, lines=4) MSG_STACK_ERROR					"Erreur - memoire statique ecrasee"
#define(length=20, lines=1) MSG_CALIBRATE_E					"Calibrer E"
//#define(length=20, lines=1) MSG_RESET_CALIBRATE_E			"Reset E Cal." 
#define(length=20, lines=8) MSG_E_CAL_KNOB					"Tournez le bouton pour que la marque atteigne le corps de l extruder, puis appuyez sur le bouton."

//#define(length=20, lines=1) MSG_FARM_CARD_MENU			"impression mode ferme" 
#define(length=20, lines=8) MSG_MARK_FIL					"marquez le filament à 100mm du corps de l extrudeur. Cliquez quand fait."
#define(length=20, lines=8) MSG_CLEAN_NOZZLE_E				"E calibration terminee. Merci de nettoyer la buse. Cliquez quand fait."
#define(length=20, lines=3) MSG_WAITING_TEMP				"Attente refroidissement buse et plateau"
#define(length=20, lines=2) MSG_FILAMENT_CLEAN				"Couleur nette?"
#define(length=20, lines=1) MSG_UNLOADING_FILAMENT			"Ejection filament"
#define(length=20, lines=10) MSG_PAPER						"Placer une feuille de papier sous la buse durant la calibration des 4 premiers points. Si la buse deplace la feuille, eteindre immediatement l imprimante."

#define(length=18) MSG_BED_CORRECTION_MENU					"Correction Plat."
//#define(length=14,lines=1) MSG_BED_CORRECTION_LEFT		"Gauche    [um]"
//#define(length=14,lines=1) MSG_BED_CORRECTION_RIGHT		"Droit     [um]"
//#define(length=14,lines=1) MSG_BED_CORRECTION_FRONT		"Avant     [um]"
//#define(length=14,lines=1) MSG_BED_CORRECTION_REAR		"Arriere   [um]"
#define(length=14,lines=1) MSG_BED_CORRECTION_FRONT_LEFT 	"Av.Gauch a[um]"
#define(length=14,lines=1) MSG_BED_CORRECTION_FRONT_CENTR 	"Av.Centr b[um]"
#define(length=14,lines=1) MSG_BED_CORRECTION_FRONT_RIGHT 	"Av.Droit c[um]"
#define(length=14,lines=1) MSG_BED_CORRECTION_MID_RIGHT 	"Mi.Droit d[um]"
#define(length=14,lines=1) MSG_BED_CORRECTION_REAR_RIGHT 	"Ar.Droit e[um]"
#define(length=14,lines=1) MSG_BED_CORRECTION_REAR_CENTR 	"Ar.Centr f[um]"
#define(length=14,lines=1) MSG_BED_CORRECTION_REAR_LEFT 	"Ar.Gauch g[um]"
#define(length=14,lines=1) MSG_BED_CORRECTION_MID_LEFT 		"Mi.Gauch h[um]"
#define MSG_BED_CORRECTION_RESET							"RAZ"

#define MSG_MESH_BED_LEVELING								"Mesh Bed Leveling"
#define MSG_MENU_CALIBRATION								"Calibration"
#define(length=19, lines=1) MSG_TOSHIBA_FLASH_AIR_COMPATIBILITY_OFF		"SD card [normal]"
#define(length=19, lines=1) MSG_TOSHIBA_FLASH_AIR_COMPATIBILITY_ON		"SD card [FlshAir]"
#define(length=20, lines=1) MSG_PRINTER_DISCONNECTED		"Impr. deconnectee"
#define(length=20, lines=1) MSG_FINISHING_MOVEMENTS			"Termine mouvements"
#define(length=20, lines=1) MSG_PRINT_PAUSED				"Impr en pause"
#define(length=20, lines=1) MSG_RESUMING_PRINT				"Reprise Impr."
#define(length=17, lines=1) MSG_PID_EXTRUDER				"Calibration PID "
#define(length=19, lines=1) MSG_SET_TEMPERATURE				"Def. temperature:"
#define(length=20, lines=1) MSG_PID_FINISHED				"PID cal. effectue"
#define(length=20, lines=1) MSG_PID_RUNNING					"PID cal.         "

#define(length=17, lines=1) MSG_CALIBRATE_PINDA				"Calibre"
#define(length=17, lines=1) MSG_CALIBRATION_PINDA_MENU		"PINDA Temp. cal."
#define(length=20, lines=4) MSG_PINDA_NOT_CALIBRATED		"La calibration de temperature n' a pas encore ete faite"
#define(length=20, lines=1) MSG_PINDA_PREHEAT				"chaffage PINDA"
#define(length=20, lines=1) MSG_TEMP_CALIBRATION			"Temp. cal.          "
#define(length=20, lines=5) MSG_TEMP_CALIBRATION_DONE		"calibration temperature terminee. Cliquez pour continuer."
#define(length=20, lines=1) MSG_TEMP_CALIBRATION_ON			"Temp. cal. [ON]"
#define(length=20, lines=1) MSG_TEMP_CALIBRATION_OFF		"Temp. cal. [OFF]"

#define(length=20, lines=1) MSG_PREPARE_FILAMENT			"Preparer nouv.filam."
#define(length=19, lines=1) MSG_ALL							"Tous"
#define(length=19, lines=1) MSG_USED						"Utilise durant impr"
#define(length=19, lines=1) MSG_CURRENT						"Actuel"
#define(length=20, lines=1)	MSG_CHOOSE_EXTRUDER				"Choisir extrudeur:"
#define(length=17, lines=1) MSG_EXTRUDER					"Extrudeur"
#define(length=17, lines=1) MSG_EXTRUDER_1					"Extrudeur 1"
#define(length=17, lines=1) MSG_EXTRUDER_2					"Extrudeur 2"
#define(length=17, lines=1) MSG_EXTRUDER_3					"Extrudeur 3"
#define(length=17, lines=1) MSG_EXTRUDER_4					"Extrudeur 4"
#define(length=17, lines=1) MSG_DATE						"Date:"
#define(length=19, lines=1) MSG_XYZ_DETAILS					"XYZ cal. details"
#define(length=20, lines=1)	MSG_Y_DISTANCE_FROM_MIN			"Y distance from min:"
#define(length=12, lines=1)	MSG_LEFT						"Gauche:"
#define(length=12, lines=1) MSG_CENTER						"Centre:"
#define(length=12, lines=1) MSG_RIGHT						"Droit:"
#define(length=15, lines=1) MSG_MEASURED_SKEW				"Mesure angle:"
#define(length=15, lines=1) MSG_SLIGHT_SKEW					"Leger angle:"
#define(length=15, lines=1) MSG_SEVERE_SKEW					"Fort angle:"
#define(length=20, lines=4) MSG_DEFAULT_SETTINGS_LOADED		"Default settings loaded"
#define(length=17, lines=1) MSG_SORT_TIME					"Tri: [Date]"
#define(length=17, lines=1) MSG_SORT_ALPHA					"Tri: [Alphabet]"
#define(length=17, lines=1) MSG_SORT_NONE					"Tri: [Aucun]"
#define(length=20, lines=1) MSG_SORTING						"Tri fichiers"
#define(length=20, lines=2) MSG_FILE_INCOMPLETE				"Fichier incomplet, continuer?"
#define(length=17, lines=1) MSG_WIZARD						"Assistant"
#define(length=20, lines=7)	MSG_WIZARD_WELCOME				"Bonjour, je suis votre imprimante Original Prusa i3. Voulez-vous que je vous guide durant la mise en route?"
#define(length=20, lines=8) MSG_WIZARD_QUIT					"Vous pouvez reprendre l'assistant depuis Calibration -> Assistant"
#define(length=20, lines=8) MSG_WIZARD_SELFTEST				"Je fais commencer par un auto test pour controler les parametres essentiels."
#define(length=20, lines=8) MSG_WIZARD_CALIBRATION_FAILED	"Merci de lire la notice pour corriger le probleme. Puis reprennez en rebootant l'imprimante."
#define(length=20, lines=8) MSG_WIZARD_XYZ_CAL				"Je vais lancer la calibration xyz maintenant. ca prendra environ 12 mins."
#define(length=20, lines=2) MSG_WIZARD_FILAMENT_LOADED		"Filament charge?"
#define(length=20, lines=8) MSG_WIZARD_Z_CAL				"Je lance la calibrtion z maintenant."
#define(length=20, lines=4) MSG_WIZARD_WILL_PREHEAT			"Je vais prechauffer la buse piur du PLA."
#define(length=20, lines=3) MSG_WIZARD_HEATING				"Chauffage buse. Attendre SVP."
#define(length=20, lines=8) MSG_WIZARD_V2_CAL				"Maintenant je vais calibrer la distance entre le plateua et la buse."
#define(lenght=20, lines=14) MSG_WIZARD_V2_CAL_2			"Je vais imprimer une ligne et vous devrez baisser la buse avec le bouton jusqu'a atteindre la sitance optimale. Regardez les photos dasn le manuel au chapitre Calibration."
#define(lenght=17, lines=1) MSG_V2_CALIBRATION				"Cal. prem. couche"
#define(length=20, lines=8) MSG_WIZARD_DONE					"Et voila. Bonne impression!"
#define(length=20, lines=8) MSG_WIZARD_LOAD_FILAMENT		"Merci d'inserer le filament PLA dans l'extrudeur, puis appuez sur le bouton pour le charger."
#define(length=20, lines=7) MSG_WIZARD_RERUN				"Le Wizard va effecer toutes les calibration precedentes et recommencer au debut. Continuer?"
#define(length=20, lines=7) MSG_WIZARD_REPEAT_V2_CAL		"Voulez vous recommencer la derniere etape pour juste lire la distance entre la buse et le plateau?"
#define(length=20, lines=7) MSG_WIZARD_CLEAN_HEATBED		"Merci de nettoyer le plateau puis appuyez sur le bouton."
#define(length=20, lines=2) MSG_WIZARD_PLA_FILAMENT			"Filament PLA en place?"
#define(length=20, lines=8) MSG_WIZARD_INSERT_CORRECT_FILAMENT	"Merci de charger le filament PLA puis relancez le wizard en rebootant l'imprimante."
#define(length=20, lines=2) MSG_PLA_FILAMENT_LOADED			"Filament PLA charge?"
#define(length=20, lines=4) MSG_PLEASE_LOAD_PLA				"Merci de charger le filament PLA d abord."
#define(length=20, lines=8) MSG_FILE_CNT					"Certains fichiers non tries. Limite de tri: 100 fichiers par repertoire."
