#define WELCOME_MSG                         CUSTOM_MENDEL_NAME " pronta."
#define MSG_SD_INSERTED                     "SD inserita"
#define MSG_SD_REMOVED                      "SD rimossa"
#define MSG_MAIN                            "Menu principale"
#define MSG_DISABLE_STEPPERS                "Disabilit motori"
#define MSG_AUTO_HOME                       "Trova origine"
#define MSG_SET_HOME_OFFSETS                "Set home offsets"
#define MSG_SET_ORIGIN                      "Set origin"
#define MSG_COOLDOWN                        "Raffredda"
#define MSG_SWITCH_PS_ON                    "Switch power on"
#define MSG_SWITCH_PS_OFF                   "Switch power off"
#define MSG_MOVE_AXIS                       "Muovi asse"
#define MSG_MOVE_X                          "Muovi X"
#define MSG_MOVE_Y                          "Muovi Y"
#define MSG_MOVE_Z                          "Muovi Z"
#define MSG_MOVE_E                          "Muovi Estrusore"
#define MSG_MOVE_01MM                       "Move 0.1mm"
#define MSG_MOVE_1MM                        "Move 1mm"
#define MSG_MOVE_10MM                       "Move 10mm"
#define MSG_SPEED                           "Velocita"
#define MSG_NOZZLE                          "Ugello"
#define MSG_NOZZLE1                         "Nozzle2"
#define MSG_NOZZLE2                         "Nozzle3"
#define MSG_BED                             "Letto"
#define MSG_FAN_SPEED                       "Velocita vent."
#define MSG_FLOW                            "Flusso"
#define MSG_TEMPERATURE                     "Temperatura"
#define MSG_MOTION                          "Motion"
#define MSG_VOLUMETRIC                      "Filament"
#define MSG_VOLUMETRIC_ENABLED		    	"E in mm3"
#define MSG_STORE_EPROM                     "Store memory"
#define MSG_LOAD_EPROM                      "Load memory"
#define MSG_RESTORE_FAILSAFE                "Restore failsafe"
#define MSG_REFRESH                         "\xF8" "Refresh"
#define MSG_WATCH                           "Schermata info"
#define MSG_TUNE                            "Regola"
#define MSG_PAUSE_PRINT                     "Metti in pausa"
#define MSG_RESUME_PRINT                    "Riprendi stampa"
#define MSG_STOP_PRINT                      "Arresta stampa"
#define MSG_CARD_MENU                       "Stampa da SD"
#define MSG_NO_CARD                         "Nessuna SD"
#define MSG_DWELL                           "Sospensione..."
#define MSG_USERWAIT                        "Attendendo utente"
#define MSG_RESUMING                        "Riprendi stampa"
#define MSG_PRINT_ABORTED                   "Stampa abortita"
#define MSG_NO_MOVE                         "Nessun movimento."
#define MSG_KILLED                          "IN TILT."
#define MSG_STOPPED                         "ARRESTATO."
#define MSG_FILAMENTCHANGE                  "Camb. filamento"
#define MSG_INIT_SDCARD                     "Init. SD card"
#define MSG_CNG_SDCARD                      "Change SD card"
#define MSG_ZPROBE_OUT                      "Z probe out. bed"
#define MSG_POSITION_UNKNOWN                "Home X/Y before Z"
#define MSG_ZPROBE_ZOFFSET                  "Z Offset"
#define MSG_BABYSTEP_X                      "Babystep X"
#define MSG_BABYSTEP_Y                      "Babystep Y"
#define MSG_BABYSTEP_Z                      "Compensazione Z"
#define MSG_ADJUSTZ			    			"Autoregolare Z?"
#define MSG_PICK_Z			    			"Pick print"

#define MSG_SETTINGS                        "Impostazioni"
#define MSG_PREHEAT                         "Preriscalda"
#define MSG_HEATING                         "Riscaldamento..."
#define MSG_SUPPORT 						"Support"
#define MSG_YES								"Si"
#define MSG_NO								"No"
#define MSG_NOT_LOADED 						"Fil. non caricato"
#define MSG_NOT_COLOR 						"Colore non puro"
#define MSG_LOADING_COLOR					"Caricando colore"
#define MSG_CHANGE_SUCCESS					"Cambio riuscito!"
#define MSG_PRESS							"e cliccare manopola"
#define MSG_INSERT_FILAMENT					"Inserire filamento"
#define MSG_CHANGING_FILAMENT				"Cambiando filam."

#define MSG_PLEASE_WAIT						"Aspetta"
#define MSG_PREHEAT_NOZZLE                  "Preris. ugello!"
#define MSG_HEATING_COMPLETE                "Riscald. completo"
#define MSG_BED_HEATING                     "Riscald. letto"
#define MSG_BED_DONE                        "Piatto fatto."
#define MSG_ERROR                        	"ERRORE:"
#define MSG_CORRECTLY						"Cambiato corr.?"
#define MSG_LOADING_FILAMENT				"Caricando filam."
#define MSG_UNLOAD_FILAMENT                 "Scarica filamento"
#define MSG_LOAD_FILAMENT                   "Carica filamento"

#define MSG_SILENT_MODE_ON		    "Modo [silenzioso]"
#define MSG_SILENT_MODE_OFF		    "Mode      [forte]" 
#define MSG_REBOOT			    "Riavvia stampante"
#define MSG_TAKE_EFFECT			    " per attualizzare"

#define MSG_Enqueing                        "enqueing \""
#define MSG_POWERUP                         "PowerUp"
#define MSG_CONFIGURATION_VER               " Last Updated: "
#define MSG_FREE_MEMORY                     " Free Memory: "
#define MSG_PLANNER_BUFFER_BYTES            "  PlannerBufferBytes: "
#define MSG_OK                              "ok"
#define MSG_ERR_CHECKSUM_MISMATCH           "checksum mismatch, Last Line: "
#define MSG_ERR_NO_CHECKSUM                 "No Checksum with line number, Last Line: "
#define MSG_BEGIN_FILE_LIST                 "Begin file list"
#define MSG_END_FILE_LIST                   "End file list"
#define MSG_M104_INVALID_EXTRUDER           "M104 Invalid extruder "
#define MSG_M105_INVALID_EXTRUDER           "M105 Invalid extruder "
#define MSG_M200_INVALID_EXTRUDER           "M200 Invalid extruder "
#define MSG_M218_INVALID_EXTRUDER           "M218 Invalid extruder "
#define MSG_M221_INVALID_EXTRUDER           "M221 Invalid extruder "
#define MSG_ERR_NO_THERMISTORS              "No thermistors - no temperature"
#define MSG_M109_INVALID_EXTRUDER           "M109 Invalid extruder "
#define MSG_M115_REPORT                     "FIRMWARE_NAME:Marlin V1.0.2; Sprinter/grbl mashup for gen6 FIRMWARE_URL:" FIRMWARE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" CUSTOM_MENDEL_NAME " EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) " UUID:" MACHINE_UUID "\n"
#define MSG_ERR_KILLED                      "Printer halted. kill() called!"
#define MSG_ERR_STOPPED                     "Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)"
#define MSG_RESEND                          "Resend: "
#define MSG_M119_REPORT                     "Reporting endstop status"
#define MSG_ENDSTOP_HIT                     "TRIGGERED"
#define MSG_ENDSTOP_OPEN                    "open"
#define MSG_SD_CANT_OPEN_SUBDIR             "Cannot open subdir"
#define MSG_SD_INIT_FAIL                    "SD init fail"
#define MSG_SD_VOL_INIT_FAIL                "volume.init failed"
#define MSG_SD_OPENROOT_FAIL                "openRoot failed"
#define MSG_SD_CARD_OK                      "SD card ok"
#define MSG_SD_WORKDIR_FAIL                 "workDir open failed"
#define MSG_SD_OPEN_FILE_FAIL               "open failed, File: "
#define MSG_SD_FILE_OPENED                  "File opened: "
#define MSG_SD_FILE_SELECTED                "File selected"
#define MSG_SD_WRITE_TO_FILE                "Writing to file: "
#define MSG_SD_PRINTING_BYTE                "SD printing byte "
#define MSG_SD_NOT_PRINTING                 "Not SD printing"
#define MSG_SD_ERR_WRITE_TO_FILE            "error writing to file"
#define MSG_SD_CANT_ENTER_SUBDIR            "Cannot enter subdir: "
#define MSG_STEPPER_TOO_HIGH                "Steprate too high: "
#define MSG_ENDSTOPS_HIT                    "endstops hit: "
#define MSG_ERR_COLD_EXTRUDE_STOP           " cold extrusion prevented"
#define MSG_BABYSTEPPING_X                  "Babystepping X"
#define MSG_BABYSTEPPING_Y                  "Babystepping Y"
#define MSG_BABYSTEPPING_Z                  "Adjusting Z"
#define MSG_SERIAL_ERROR_MENU_STRUCTURE     "Error in menu structure"

#define MSG_LANGUAGE_NAME		    "Italiano"
#define MSG_LANGUAGE_SELECT		    "Seleziona lingua"
#define MSG_PRUSA3D			    "prusa3d.com"
#define MSG_PRUSA3D_FORUM		    "forum.prusa3d.com"
#define MSG_PRUSA3D_HOWTO		    "howto.prusa3d.com"

#define MSG_SELFTEST_ERROR		    "Autotest negativo"
#define MSG_SELFTEST_PLEASECHECK	    "Verificare:"	
#define MSG_SELFTEST_NOTCONNECTED	    "Non connesso"
#define MSG_SELFTEST_HEATERTHERMISTOR	    "Riscald./Termist."
#define MSG_SELFTEST_BEDHEATER		    "Letto/Riscald."
#define MSG_SELFTEST_WIRINGERROR	    "Errore cablaggio"
#define MSG_SELFTEST_ENDSTOPS		    "Finecorsa (2)"
#define MSG_SELFTEST_MOTOR		    "Motore"
#define MSG_SELFTEST_ENDSTOP		    "Finecorsa"
#define MSG_SELFTEST_ENDSTOP_NOTHIT	    "Finec. fuori por."
#define MSG_SELFTEST_OK			    "Autotest OK"

#define(length=20) MSG_SELFTEST_FAN					"Prova del ventilator";
#define(length=20) MSG_SELFTEST_COOLING_FAN			"Vent di stampa ant.?";
#define(length=20) MSG_SELFTEST_EXTRUDER_FAN        "Vent SX sull'ugello?";
#define MSG_SELFTEST_FAN_YES				"Gira";
#define MSG_SELFTEST_FAN_NO					"Non si gira";

#define MSG_STATS_TOTALFILAMENT		    "Filamento tot:"
#define MSG_STATS_TOTALPRINTTIME	    "Tempo stampa tot:"
#define MSG_STATS_FILAMENTUSED		    "Filamento usato:"
#define MSG_STATS_PRINTTIME		    "Tempo di stampa:"
#define MSG_SELFTEST_START		    "Avvia autotest"
#define MSG_SELFTEST_CHECK_ENDSTOPS	    "Verifica finecorsa"
#define MSG_SELFTEST_CHECK_HOTEND	    "Verifica ugello"  
#define MSG_SELFTEST_CHECK_X		    "Verifica asse X"
#define MSG_SELFTEST_CHECK_Y		    "Verifica asse Y"
#define MSG_SELFTEST_CHECK_Z		    "Verifica asse Z"
#define MSG_SELFTEST_CHECK_BED		    "Verifica letto"
#define MSG_SELFTEST_CHECK_ALLCORRECT	    "Nessun errore"
#define MSG_SELFTEST			    "Autotest"
#define MSG_SELFTEST_FAILED		    "Autotest fallito"
#define MSG_STATISTICS			    "Statistiche"
#define MSG_USB_PRINTING		    "Stampa da USB"
#define MSG_HOMEYZ                          "Calibra Z"
#define MSG_HOMEYZ_PROGRESS                 "Calibrando Z"
#define MSG_HOMEYZ_DONE		            "Calibrazione OK"



#define MSG_SHOW_END_STOPS					"Stato finecorsa"
#define MSG_CALIBRATE_BED					"Calibra XYZ"
#define MSG_CALIBRATE_BED_RESET					"Reset XYZ calibr."

#define MSG_MOVE_CARRIAGE_TO_THE_TOP 				"Calibrazione XYZ. Ruotare la manopola per alzare il carrello Z fino all'altezza massima. Click per terminare."
#define MSG_MOVE_CARRIAGE_TO_THE_TOP_Z 				"Calibrazione Z. Ruotare la manopola per alzare il carrello Z fino all'altezza massima. Click per terminare."

#define MSG_CONFIRM_NOZZLE_CLEAN					"Pulire l'ugello per la calibrazione, poi fare click."
#define MSG_CONFIRM_CARRIAGE_AT_THE_TOP				"I carrelli Z sin/des sono altezza max?"

#define MSG_FIND_BED_OFFSET_AND_SKEW_LINE1			"Ricerca del letto punto di calibraz."
#define MSG_FIND_BED_OFFSET_AND_SKEW_LINE2			" su 4"
#define MSG_IMPROVE_BED_OFFSET_AND_SKEW_LINE1		"Perfezion. il letto punto di calibraz."
#define MSG_IMPROVE_BED_OFFSET_AND_SKEW_LINE2		" su 9"
#define MSG_MEASURE_BED_REFERENCE_HEIGHT_LINE1		"Misurare l'altezza di riferimento del punto di calibrazione"
#define MSG_MEASURE_BED_REFERENCE_HEIGHT_LINE2		" su 9"

#define MSG_BED_SKEW_OFFSET_DETECTION_POINT_NOT_FOUND		"Calibrazione XYZ fallita. Il punto di calibrazione sul letto non e' stato trovato."
#define MSG_BED_SKEW_OFFSET_DETECTION_FITTING_FAILED		"Calibrazione XYZ fallita. Si prega di consultare il manuale."
#define MSG_BED_SKEW_OFFSET_DETECTION_PERFECT			"Calibrazione XYZ OK. Gli assi X/Y sono perpendicolari. Complimenti!"
#define MSG_BED_SKEW_OFFSET_DETECTION_SKEW_MILD			"Calibrazion XYZ corretta. Assi X/Y leggermente storti. Ben fatto!"
#define MSG_BED_SKEW_OFFSET_DETECTION_SKEW_EXTREME		"Calibrazion XYZ corretta. La distorsione verra' automaticamente compensata."
#define MSG_BED_SKEW_OFFSET_DETECTION_FAILED_FRONT_LEFT_FAR	"Calibrazione XYZ fallita. Punto anteriore sinistro non raggiungibile."
#define MSG_BED_SKEW_OFFSET_DETECTION_FAILED_FRONT_RIGHT_FAR	"Calibrazione XYZ fallita. Punto anteriore destro non raggiungibile."
#define MSG_BED_SKEW_OFFSET_DETECTION_FAILED_FRONT_BOTH_FAR	"Calibrazione XYZ fallita. Punti anteriori non raggiungibili."
#define MSG_BED_SKEW_OFFSET_DETECTION_WARNING_FRONT_LEFT_FAR	"Calibrazione XYZ compromessa. Punto anteriore sinistro non raggiungibile."
#define MSG_BED_SKEW_OFFSET_DETECTION_WARNING_FRONT_RIGHT_FAR	"Calibrazione XYZ compromessa. Punto anteriore destro non raggiungibile."
#define MSG_BED_SKEW_OFFSET_DETECTION_WARNING_FRONT_BOTH_FAR	"Calibrazione XYZ compromessa. Punti anteriori non raggiungibili."

#define MSG_BED_LEVELING_FAILED_POINT_LOW				"Livellamento letto fallito.NoRispSensor Residui su ugello? In attesa di reset."
#define MSG_BED_LEVELING_FAILED_POINT_HIGH				"Livellamento letto fallito.Risp sensore troppo prestoIn attesa di reset."
#define MSG_BED_LEVELING_FAILED_PROBE_DISCONNECTED		"Livellamento letto fallito. Sensore discon. o Cavo Dann. In attesa di reset."

#define MSG_NEW_FIRMWARE_AVAILABLE						"Nuova versione del firmware disponibile"
#define MSG_NEW_FIRMWARE_PLEASE_UPGRADE					"Prega aggiorna."

#define MSG_FOLLOW_CALIBRATION_FLOW						"Stampante ancora non calibrata. Si prega di seguire il manuale, capitolo PRIMI PASSI, sezione della calibrazione."
#define MSG_BABYSTEP_Z_NOT_SET							"Distanza tra la punta dell'ugello e la superficie del letto non ancora imposta. Si prega di seguire il manuale, capitolo First steps, sezione First layer calibration."

#define MSG_BED_CORRECTION_MENU							"Correz. liv.letto"
#define MSG_BED_CORRECTION_LEFT							"Lato sinistro"
#define MSG_BED_CORRECTION_RIGHT						"Lato destro"
#define MSG_BED_CORRECTION_FRONT						"Lato ateriore"
#define MSG_BED_CORRECTION_REAR							"Lato posteriore"
#define MSG_BED_CORRECTION_RESET						"Reset"			

#define MSG_MESH_BED_LEVELING							"Mesh livel. letto"
#define MSG_MENU_CALIBRATION							"Calibrazione"
#define MSG_TOSHIBA_FLASH_AIR_COMPATIBILITY_OFF					"SD card [normal]"
#define MSG_TOSHIBA_FLASH_AIR_COMPATIBILITY_ON					"SD card [FlshAir]"

#define MSG_LOOSE_PULLEY								"Puleggia lenta"
#define MSG_FILAMENT_LOADING_T0							"Inserire filamento nell'estrusore 1. Click per continuare."
#define MSG_FILAMENT_LOADING_T1							"Inserire filamento nell'estrusore 2. Click per continuare."
#define MSG_FILAMENT_LOADING_T2							"Inserire filamento nell'estrusore 3. Click per continuare."
#define MSG_FILAMENT_LOADING_T3							"Inserire filamento nell'estrusore 4. Click per continuare."
#define MSG_CHANGE_EXTR									"Cambio estrusore."
#define MSG_FIL_LOADED_CHECK							"Filamento caricato?"
#define MSG_FIL_TUNING									"Girare la manopola per regolare il filamento"
#define MSG_FIL_ADJUSTING								"Filamento in fase di regolazione. Attendere prego."
#define MSG_CONFIRM_NOZZLE_CLEAN_FIL_ADJ				"I filamenti sono regolati. Si prega di pulire l'ugello per la calibrazione. Click per continuare."
#define MSG_CALIBRATE_E									"Calibra E"
#define MSG_E_CAL_KNOB									"Girare la manopola affinche' il segno raggiunga il corpo dell'estrusore. Click per continuare."
#define MSG_MARK_FIL									"Segnare il filamento a 100 mm di distanza dal corpo dell'estrusore. Click per continuare."
#define MSG_CLEAN_NOZZLE_E								"Calibrazione E terminata. Si prega di pulire l'ugello. Click per continuare."
#define MSG_WAITING_TEMP								"In attesa del raffreddamento della testina e del piatto"
#define MSG_FILAMENT_CLEAN								"Il colore e' nitido?"
#define MSG_UNLOADING_FILAMENT							"Rilasc. filamento"
#define MSG_PAPER										"Porre un foglio sotto l'ugello durante la calibrazione dei primi 4 punti. In caso l'ugello muova il foglio spegnere prontamente la stampante."