/**
 * Italian
 *
 * LCD Menu Messages
 * Please note these are limited to 17 characters!
 *
 */

#define WELCOME_MSG                         CUSTOM_MENDEL_NAME " pronto."
#define MSG_SD_INSERTED                     "SD Card inserita"
#define MSG_SD_REMOVED                      "SD Card rimossa"
#define MSG_MAIN                            "Menu principale"
#define MSG_DISABLE_STEPPERS                "Disabilita Motori"
#define MSG_AUTO_HOME                       "Auto Home"
#define MSG_COOLDOWN                        "Raffredda"
#define MSG_MOVE_AXIS                       "Muovi Asse"
#define MSG_MOVE_X                          "Muovi X"
#define MSG_MOVE_Y                          "Muovi Y"
#define MSG_MOVE_Z                          "Muovi Z"
#define MSG_MOVE_E                          "Estrusore"
#define MSG_SPEED                           "Velcità"
#define MSG_NOZZLE                          "Ugello"
#define MSG_BED                             "Piatto"
#define MSG_FAN_SPEED                       "Ventola"
#define MSG_FLOW                            "Flusso"
#define MSG_TEMPERATURE                     "Temperatura"
#define MSG_WATCH                           "Guarda"
#define MSG_TUNE                            "Adatta"
#define MSG_PAUSE_PRINT                     "Pausa"
#define MSG_RESUME_PRINT                    "Riprendi stampa"
#define MSG_STOP_PRINT                      "Arresta stampa"
#define MSG_CARD_MENU                       "Menu SD Carta"
#define MSG_NO_CARD                         "No SD Carta"
#define MSG_DWELL                           "Sospensione..."
#define MSG_USERWAIT                        "Attendi Utente..."
#define MSG_RESUMING                        "Riprendi Stampa"
#define MSG_PRINT_ABORTED                   "Stampa abortita"
#define MSG_NO_MOVE                         "Nessun Movimento"
#define MSG_KILLED                          "UCCISO "
#define MSG_STOPPED                         "ARRESTATO "
#define MSG_FILAMENTCHANGE                  "Cambiare filamento"
#define MSG_BABYSTEP_Z                      "Babystep Z"
#define MSG_ADJUSTZ							"Auto regolare Z ?"
#define MSG_PICK_Z							"Vyberte vytisk"
#define MSG_SETTINGS                         "Impostazioni"
#define MSG_PREHEAT                         "Preriscalda"
#define MSG_UNLOAD_FILAMENT                 "Scaricare fil."
#define MSG_LOAD_FILAMENT                 "Caricare filamento"
#define MSG_ERROR                        "ERROR:"
#define MSG_PREHEAT_NOZZLE                       "Preris. ugello!"
#define MSG_SUPPORT "Support"
#define MSG_CORRECTLY			"Cambiato corr.?"
#define MSG_YES					"Si"
#define MSG_NO					"No"
#define MSG_NOT_LOADED 			"Fil. no cargado"
#define MSG_NOT_COLOR 			"Color no claro"
#define MSG_LOADING_FILAMENT	"Cargando fil."
#define MSG_PLEASE_WAIT			"Aspetta"
#define MSG_LOADING_COLOR		"Cargando color"
#define MSG_CHANGE_SUCCESS		"Cambia. riuscito!"
#define MSG_PRESS				"Y pulse el mando"
#define MSG_INSERT_FILAMENT		"Inserire filamento"
#define MSG_CHANGING_FILAMENT	"Mutevole fil.!"
#define MSG_SILENT_MODE_ON					"Modo     [silenzioso]"
#define MSG_SILENT_MODE_OFF					"Modo [piu forza]" 
#define MSG_REBOOT							"Riavvio la stamp."
#define MSG_TAKE_EFFECT						" per mostrare i camb."											
#define MSG_HEATING                         "Riscaldamento..."
#define MSG_HEATING_COMPLETE                "Riscaldamento fatto."
#define MSG_BED_HEATING                     "Piatto riscaldam."
#define MSG_BED_DONE                        "Piatto fatto."
#define MSG_LANGUAGE_NAME					"Italiano"
#define MSG_LANGUAGE_SELECT					"Selez. la lingua"
#define MSG_PRUSA3D					"prusa3d.com"
#define MSG_PRUSA3D_FORUM					"forum.prusa3d.com"
#define MSG_PRUSA3D_HOWTO					"howto.prusa3d.com"


// Do not translate those!

#define MSG_Enqueing                        "enqueing \""
#define MSG_POWERUP                         "PowerUp"
#define MSG_CONFIGURATION_VER               " Last Updated: "
#define MSG_FREE_MEMORY                     " Free Memory: "
#define MSG_PLANNER_BUFFER_BYTES            "  PlannerBufferBytes: "
#define MSG_OK                              "ok"
#define MSG_ERR_CHECKSUM_MISMATCH           "checksum mismatch, Last Line: "
#define MSG_ERR_NO_CHECKSUM                 "No Checksum with line number, Last Line: "
#define MSG_BEGIN_FILE_LIST                 "Begin file list"
#define MSG_END_FILE_LIST                   "End file list"
#define MSG_M104_INVALID_EXTRUDER           "M104 Invalid extruder "
#define MSG_M105_INVALID_EXTRUDER           "M105 Invalid extruder "
#define MSG_M200_INVALID_EXTRUDER           "M200 Invalid extruder "
#define MSG_M218_INVALID_EXTRUDER           "M218 Invalid extruder "
#define MSG_M221_INVALID_EXTRUDER           "M221 Invalid extruder "
#define MSG_ERR_NO_THERMISTORS              "No thermistors - no temperature"
#define MSG_M109_INVALID_EXTRUDER           "M109 Invalid extruder "
#define MSG_M115_REPORT                     "FIRMWARE_NAME:Marlin V1.0.2; Sprinter/grbl mashup for gen6 FIRMWARE_URL:" FIRMWARE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" CUSTOM_MENDEL_NAME " EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) " UUID:" MACHINE_UUID "\n"
#define MSG_ERR_KILLED                      "Printer halted. kill() called!"
#define MSG_ERR_STOPPED                     "Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)"
#define MSG_RESEND                          "Resend: "
#define MSG_M119_REPORT                     "Reporting endstop status"
#define MSG_ENDSTOP_HIT                     "TRIGGERED"
#define MSG_ENDSTOP_OPEN                    "open"
#define MSG_SD_CANT_OPEN_SUBDIR             "Cannot open subdir"
#define MSG_SD_INIT_FAIL                    "SD init fail"
#define MSG_SD_VOL_INIT_FAIL                "volume.init failed"
#define MSG_SD_OPENROOT_FAIL                "openRoot failed"
#define MSG_SD_CARD_OK                      "SD card ok"
#define MSG_SD_WORKDIR_FAIL                 "workDir open failed"
#define MSG_SD_OPEN_FILE_FAIL               "open failed, File: "
#define MSG_SD_FILE_OPENED                  "File opened: "
#define MSG_SD_FILE_SELECTED                "File selected"
#define MSG_SD_WRITE_TO_FILE                "Writing to file: "
#define MSG_SD_PRINTING_BYTE                "SD printing byte "
#define MSG_SD_NOT_PRINTING                 "Not SD printing"
#define MSG_SD_ERR_WRITE_TO_FILE            "error writing to file"
#define MSG_SD_CANT_ENTER_SUBDIR            "Cannot enter subdir: "
#define MSG_STEPPER_TOO_HIGH                "Steprate too high: "
#define MSG_ENDSTOPS_HIT                    "endstops hit: "
#define MSG_ERR_COLD_EXTRUDE_STOP           " cold extrusion prevented"
#define MSG_BABYSTEPPING_X                  "Babystepping X"
#define MSG_BABYSTEPPING_Y                  "Babystepping Y"
#define MSG_BABYSTEPPING_Z                  "Adjusting Z"
#define MSG_SERIAL_ERROR_MENU_STRUCTURE     "Error in menu structure"
#define MSG_SET_HOME_OFFSETS                "Set home offsets"
#define MSG_SET_ORIGIN                      "Set origin"
#define MSG_SWITCH_PS_ON                    "Switch power on"
#define MSG_SWITCH_PS_OFF                   "Switch power off"
#define MSG_NOZZLE1                         "Nozzle2"
#define MSG_NOZZLE2                         "Nozzle3"
#define MSG_FLOW0                           "Flow 0"
#define MSG_FLOW1                           "Flow 1"
#define MSG_FLOW2                           "Flow 2"
#define MSG_CONTROL                         "Control"
#define MSG_MIN                             " \002 Min"
#define MSG_MAX                             " \002 Max"
#define MSG_FACTOR                          " \002 Fact"
#define MSG_MOTION                          "Motion"
#define MSG_VOLUMETRIC                      "Filament"
#define MSG_VOLUMETRIC_ENABLED		        "E in mm3"
#define MSG_STORE_EPROM                     "Store memory"
#define MSG_LOAD_EPROM                      "Load memory"
#define MSG_RESTORE_FAILSAFE                "Restore failsafe"
#define MSG_REFRESH                         "\xF8" "Refresh"
#define MSG_INIT_SDCARD                     "Init. SD card"
#define MSG_CNG_SDCARD                      "Change SD card"
#define MSG_BABYSTEP_X                      "Babystep X"
#define MSG_BABYSTEP_Y                      "Babystep Y"
#define MSG_RECTRACT                        "Rectract"

#define MSG_HOMEYZ                          "Calibra Z"
#define MSG_HOMEYZ_PROGRESS                 "Calibrando Z"
#define MSG_HOMEYZ_DONE                     "Calibratura OK"

#define MSG_SELFTEST_ERROR                  "Autotest negativo"
#define MSG_SELFTEST_PLEASECHECK            "Verifica:"   
#define MSG_SELFTEST_NOTCONNECTED           "Non connesso"
#define MSG_SELFTEST_HEATERTHERMISTOR       "Riscald./Termistore"
#define MSG_SELFTEST_BEDHEATER              "Piastra/Riscaldatore"
#define MSG_SELFTEST_WIRINGERROR            "Errore cablaggio"
#define MSG_SELFTEST_ENDSTOPS               "Limiti corsa"
#define MSG_SELFTEST_MOTOR                  "Motore"
#define MSG_SELFTEST_ENDSTOP                "Limite corsa"
#define MSG_SELFTEST_ENDSTOP_NOTHIT         "Lim. fuoriportata"
#define MSG_SELFTEST_OK                     "Autotest OK"

#define MSG_STATS_TOTALFILAMENT             "Filamento tot:"
#define MSG_STATS_TOTALPRINTTIME            "Tempo stampa tot:"
#define MSG_STATS_FILAMENTUSED              "Filamento:"
#define MSG_STATS_PRINTTIME                 "Tempo stampa:"

#define MSG_SELFTEST_START                  "Inizia autotest"
#define MSG_SELFTEST_CHECK_ENDSTOPS         "Verifica limiti"
#define MSG_SELFTEST_CHECK_HOTEND           "Verifica lim temp" 
#define MSG_SELFTEST_CHECK_X                "Verifica asse X"
#define MSG_SELFTEST_CHECK_Y                "Verifica asse Y"
#define MSG_SELFTEST_CHECK_Z                "Verifica asse Z"
#define MSG_SELFTEST_CHECK_BED              "Verifica piastra"
#define MSG_SELFTEST_CHECK_ALLCORRECT       "Nessun errore"
#define MSG_SELFTEST                        "Autotest"
#define MSG_SELFTEST_FAILED                 "Autotest fallito"

#define MSG_STATISTICS                      "Statistiche"
#define MSG_USB_PRINTING                    "Stampa da USB"
